#!/usr/bin/env bash
# ============================================================
# Aman Agency — Deploy Script
#
# Run this on the TARGET server after copying the dist/ bundle
# produced by scripts/build.sh.
#
# What it does:
#   1. Loads backend and frontend Docker images from tarballs
#   2. Creates infra/.env from .env.example (if missing)
#   3. Patches docker-compose.yml to use pre-built images
#      (no build: keys needed — images are already loaded)
#   4. Pulls mongo / nginx / certbot from Docker Hub
#   5. Starts the full stack with production resource limits
#   6. Waits for health checks and prints a status summary
#
# Prerequisites on the target server:
#   • Docker Engine 24+ and Docker Compose v2 (docker compose)
#   • Files from dist/ copied here:
#       aman-backend.tar.gz
#       aman-frontend.tar.gz
#       aman-agency-infra.tar.gz   (contains infra/ + scripts/)
#
# Usage (run from the directory that contains the dist/ files):
#   tar xzf aman-agency-infra.tar.gz   # extract infra/ and scripts/
#   bash scripts/deploy.sh
#
# Re-deploy (after a new build):
#   bash scripts/deploy.sh             # images are reloaded, stack restarted
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
INFRA_DIR="$PROJECT_ROOT/infra"
DIST_DIR="${DIST_DIR:-$PROJECT_ROOT/dist}"   # override with env var if needed

# ── Colour helpers ────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}▶${RESET}  $*"; }
success() { echo -e "${GREEN}✅${RESET}  $*"; }
warn()    { echo -e "${YELLOW}⚠️ ${RESET}  $*"; }
die()     { echo -e "${RED}❌${RESET}  $*" >&2; exit 1; }

echo ""
echo -e "${BOLD}┌──────────────────────────────────────────────────────┐${RESET}"
echo -e "${BOLD}│  Aman Agency — Deploy                                │${RESET}"
echo -e "${BOLD}└──────────────────────────────────────────────────────┘${RESET}"
echo ""

# ── Prereqs ──────────────────────────────────────────────────
for cmd in docker; do
  command -v "$cmd" &>/dev/null || die "'$cmd' is required but not found in PATH."
done
docker compose version &>/dev/null || die "'docker compose' (v2 plugin) is required."

# ── Locate image tarballs ─────────────────────────────────────
# Look for tarballs next to this script, in $DIST_DIR, or in the cwd.
find_tarball() {
  local name="$1"
  for dir in "$SCRIPT_DIR" "$DIST_DIR" "$(pwd)"; do
    [[ -f "$dir/$name" ]] && { echo "$dir/$name"; return; }
  done
  die "Cannot find $name — make sure it is in the same directory as deploy.sh, in dist/, or in the current directory."
}

BACKEND_TAR="$(find_tarball  aman-backend.tar.gz)"
FRONTEND_TAR="$(find_tarball aman-frontend.tar.gz)"

# ── Determine image tag ───────────────────────────────────────
TAG_FILE="$(dirname "$BACKEND_TAR")/.image-tag"
if [[ -f "$TAG_FILE" ]]; then
  IMAGE_TAG="$(cat "$TAG_FILE")"
else
  IMAGE_TAG="latest"
fi
info "Image tag: $IMAGE_TAG"

# ── Step 1: Load images ───────────────────────────────────────
echo ""
info "Loading backend image from $BACKEND_TAR ..."
docker load --input "$BACKEND_TAR"
success "Backend image loaded."

info "Loading frontend image from $FRONTEND_TAR ..."
docker load --input "$FRONTEND_TAR"
success "Frontend image loaded."

# ── Step 2: Ensure infra/.env exists ─────────────────────────
echo ""
ENV_FILE="$INFRA_DIR/.env"
ENV_EXAMPLE="$INFRA_DIR/.env.example"

if [[ ! -f "$ENV_FILE" ]]; then
  if [[ -f "$ENV_EXAMPLE" ]]; then
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    warn "Created infra/.env from .env.example"
    echo ""
    echo -e "${YELLOW}  !! IMPORTANT: Edit infra/.env and fill in all secrets before"
    echo -e "     continuing. The file has been opened below for reference. !!${RESET}"
    echo ""
    echo "  Required variables:"
    grep -E "^[A-Z_]+=\s*$" "$ENV_FILE" | sed 's/=.*//' | while read -r var; do
      echo "    • $var"
    done 2>/dev/null || true
    echo ""
    read -rp "  Press ENTER once you have edited infra/.env to continue deployment... " _
    echo ""
  else
    die "infra/.env not found and no .env.example exists.\n   Create infra/.env manually — see the README for required variables."
  fi
else
  success "infra/.env exists — skipping copy."
fi

# ── Step 3: Patch compose file to use pre-loaded images ───────
# The docker-compose.yml has `build:` directives; on the target server
# we want to use the images we just loaded, so we override image: tags.
echo ""
info "Preparing compose override for pre-built images..."

OVERRIDE_FILE="$INFRA_DIR/docker-compose.images.yml"
cat > "$OVERRIDE_FILE" <<EOF
# Auto-generated by deploy.sh — do not edit manually.
# Overrides build: directives with pre-loaded image tags.
version: "3.9"
services:
  backend:
    image: aman-backend:${IMAGE_TAG}
    build: !reset null
  frontend:
    image: aman-frontend:${IMAGE_TAG}
    build: !reset null
EOF

success "Compose override written to infra/docker-compose.images.yml"

# ── Step 4: Pull third-party images ──────────────────────────
echo ""
info "Pulling mongo, nginx, certbot from Docker Hub..."
docker compose \
  -f "$INFRA_DIR/docker-compose.yml" \
  pull mongo nginx certbot 2>&1 | grep -v "^#" || true
success "Third-party images up to date."

# ── Step 5: Start the stack ───────────────────────────────────
echo ""
info "Starting Aman Agency stack..."
docker compose \
  --file "$INFRA_DIR/docker-compose.yml" \
  --file "$INFRA_DIR/docker-compose.prod.yml" \
  --file "$OVERRIDE_FILE" \
  up -d --remove-orphans

success "Stack started."

# ── Step 6: Wait for health checks ────────────────────────────
echo ""
info "Waiting for services to become healthy (up to 90 seconds)..."

wait_healthy() {
  local container="$1"
  local max_wait=90
  local elapsed=0
  local interval=5

  while [[ $elapsed -lt $max_wait ]]; do
    local status
    status=$(docker inspect --format='{{.State.Health.Status}}' "$container" 2>/dev/null || echo "missing")
    case "$status" in
      healthy) return 0 ;;
      unhealthy)
        warn "$container is unhealthy — check logs: docker logs $container"
        return 1
        ;;
    esac
    sleep $interval
    elapsed=$((elapsed + interval))
    echo -n "."
  done
  echo ""
  warn "$container did not become healthy within ${max_wait}s."
  return 1
}

HEALTHY=true
for container in aman_mongo aman_backend aman_frontend aman_nginx; do
  echo -n "  $container "
  if wait_healthy "$container"; then
    echo -e " ${GREEN}healthy${RESET}"
  else
    HEALTHY=false
  fi
done

echo ""

# ── Summary ───────────────────────────────────────────────────
echo -e "${BOLD}┌──────────────────────────────────────────────────────┐${RESET}"
if $HEALTHY; then
  echo -e "${BOLD}│  ✅  Deployment complete!                             │${RESET}"
else
  echo -e "${BOLD}│  ⚠️   Deployment finished with warnings               │${RESET}"
fi
echo -e "${BOLD}└──────────────────────────────────────────────────────┘${RESET}"
echo ""
echo "   App     →  http://$(hostname -I | awk '{print $1}' 2>/dev/null || echo "<server-ip>")"
echo "   API     →  http://$(hostname -I | awk '{print $1}' 2>/dev/null || echo "<server-ip>")/api"
echo "   Health  →  http://$(hostname -I | awk '{print $1}' 2>/dev/null || echo "<server-ip>")/api/health"
echo ""
echo "   Service logs:"
echo "     docker logs aman_backend   -f"
echo "     docker logs aman_nginx     -f"
echo "     docker logs aman_mongo     -f"
echo ""
echo "   Container status:"
docker compose \
  --file "$INFRA_DIR/docker-compose.yml" \
  --file "$INFRA_DIR/docker-compose.prod.yml" \
  --file "$OVERRIDE_FILE" \
  ps --format "table {{.Name}}\t{{.Status}}\t{{.Ports}}"
echo ""

if ! $HEALTHY; then
  echo -e "${YELLOW}  One or more services are not healthy."
  echo -e "  Run 'docker logs <container>' to diagnose.${RESET}"
  echo ""
fi

echo "  ── Next steps ─────────────────────────────────────────"
echo "  • To enable HTTPS (Let's Encrypt), set DOMAIN and"
echo "    CERTBOT_EMAIL in infra/.env then run:"
echo "      ./scripts/init-ssl.sh"
echo ""
echo "  • To redeploy after a new build, just re-run:"
echo "      bash scripts/deploy.sh"
echo ""
echo "  • To stop the stack:"
echo "      docker compose -f infra/docker-compose.yml down"
echo "  ───────────────────────────────────────────────────────"
echo ""
