/**
 * PWA Service Worker Registration
 * --------------------------------
 * Registers the Workbox-powered service worker generated by vite-plugin-pwa.
 *
 * Features:
 *  - Prompts the user when a new version is available (toast via sonner).
 *  - Skips the waiting phase automatically so the update applies on the next
 *    page reload rather than requiring a manual restart.
 *  - Gracefully degrades when the browser does not support service workers.
 */
import { registerSW } from 'virtual:pwa-register'
import { toast } from 'sonner'

export function registerServiceWorker() {
  if (typeof window === 'undefined') return
  if (!('serviceWorker' in navigator))  return

  const updateSW = registerSW({
    /**
     * Called when a new service worker is installed and waiting to activate.
     * We show a toast that lets the user reload to apply the update immediately.
     */
    onNeedRefresh() {
      toast('A new version is available!', {
        duration: Infinity,
        action: {
          label: 'Update',
          onClick: () => updateSW(true),  // skip waiting + reload
        },
        cancel: {
          label: 'Dismiss',
          onClick: () => { /* user chose to stay on current version */ },
        },
      })
    },

    /**
     * Called when the service worker has taken control and the app is fully
     * cached for offline use.
     */
    onOfflineReady() {
      toast.success('App is ready to work offline', { duration: 3000 })
    },

    /**
     * Called if the service worker fails to register.
     */
    onRegisterError(error) {
      if (import.meta.env.DEV) {
        console.warn('[PWA] Service worker registration failed:', error)
      }
    },
  })
}
